directories:
  output: build
  buildResources: build
appId: com.myfirmdata.mfd.plus
productName: myFirmDataPlus
artifactName: ${productName}-setup-${version}.${ext}
copyright: Copyright © 2019 ${author}
afterSign: js/notarize.js
asar: true
target: NSIS
icon: img/mfd.ico
publish:
  - provider: github
    owner: myFirmData
    repo: mfd_desk_plus
    private: true
nsis:
  allowToChangeInstallationDirectory: true
  oneClick: false
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  deleteAppDataOnUninstall: true
  include: build/installer.nsh
  perMachine: true
dmg:
  sign: false
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: img/mfdt.icns
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: entitlements.mac.plist
  entitlementsInherit: entitlements.mac.plist
  target:
    - dmg
    - zip
  extendInfo:
    CFBundleURLTypes:
      - CFBundleURLSchemes:
          - mfdmtg
win:
  icon: img/mfd.ico
  certificateSubjectName: Firm Data Inc
  target:
    - target: nsis
      arch:
        - x64
files: []
electronVersion: 16.0.4
